version: "2"
run:
  allow-parallel-runners: true
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forcetypeassert
    - ginkgolinter
    - gocheckcompilerdirectives
    - gocritic
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosmopolitan
    - grouper
    - importas
    - interfacebloat
    - loggercheck
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nilerr
    - noctx
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - staticcheck
    - testableexamples
    - testifylint
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - zerologlint
  settings:
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
    staticcheck:
      checks:
        - all
    tagliatelle:
      case:
        rules:
          json: snake
    testifylint:
      enable:
        - bool-compare
        - compares
        - empty
        - error-is-as
        - error-nil
        - expected-actual
        - float-compare
        - len
        - suite-dont-use-pkg
        - suite-extra-assert-call
        - suite-thelper
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
        path: (.+)_test.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/matoous/goodgeo)
        - dot
    goimports:
      local-prefixes:
        - github.com/matoous/goodgeo
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - ".*\\.pb\\.go$"
